# Generated by Django 3.1.12 on 2021-06-28 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='workshop',
        ),
        migrations.AddField(
            model_name='service',
            name='workshop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.workshop'),
            preserve_default=False,
        ),
    ]
